### PR TITLE
added http requests

### LINKED ISSUE #8: 🚀 Feature[backend]: Implement `/api/user` Endpoint
### Use Case
For our contribution application, similar to websites like [Kaggle](https://www.kaggle.com/), we will need to allow users to create accounts and log in (authentication is a more complicated task we will split between this issue and #20). This endpoint handles users so that when an account is created or when information about a user is requested, this handles those requests. Additionally, when the user wishes to modify information about the account, this endpoint is able to update and delete that information.

### Proposed Solution
Below is a set of resources and a list of action items that will help with implementing this feature. There are some modifications that need to be made to the examples on the resources below in order to complete this feature. There are three files you will need to modify to complete this ticket: `app.py`, `routes/user.py`, and `models/user.py`.

#### Action Items
- [x] implement the defined schema in the Flask-SQLAlchemy [ORM](https://www.freecodecamp.org/news/what-is-an-orm-the-meaning-of-object-relational-mapping-database-tools/). Modify the `User` class in `models/user.py` to include an `id` parameter (this can be a `db.Integer` and be the `primary_key` of the table, is unique, and is not nullable. Make sure to remove the `primary_key` field from the username column in the starter code). Additionally, add a `json()` function which returns a Python Dictionary of itself where the keys and values are all of the fields in the table except password. For creating user ids, you can create a `count` [static variable](https://www.geeksforgeeks.org/g-fact-34-class-or-static-variables-in-python) that keeps track of the number of users that are created and increments the static variable every time a new user is created to be used as the value of the newly created user id.
- [x] update `app.py` to include the `user(id)` endpoint uses the `router(id)` handler implemented in `routes/user.py`
- [x] implement the GET handler in `routes/user.py` to return all of the information about a user based on the given user ID. `get(id)` should query the `User` table based on the `id` and get the `first()` user object of that query.  Once that object is queried, if the user object is `None`(no user by that id), then it should return an empty JSON and 404. If the user object is found, then return the value of the `user.json()` method and 200.
- [x] implement the POST handler in `routes/user.py` to create a new user and return all of the information about a user. Check the incoming request's JSON body using `data = request.json`. If `username` or `password` don't exist then return an empty JSON and 400. If a user exists in the database with the same username, return an empty dictionary and 409. If this a unique new user, then create a new `User` object with the corresponding username and password and use the corresponding `user.save_to_db()` function. Return the value of `user.json()` and 201.
- [x] implement the PUT handler in `routes/user.py` to edit information about an existing user. Check the incoming request's JSON body using `data = request.json`. If `username` or `password` don't exist then return an empty JSON and 400. Check if the user is in the database. If the user is not in the database, then return an empty dictionary and 404. If the user is found then update the values of the user object and save to the database using the corresponding `user.save_to_db()` function. Return the value of `user.json()` and 200.
- [x] implement the DELETE handler in `routes/user.py` to delete an existing user. Check if the user is in the database. If the user is not in the database, then return an empty dictionary and 404. If the user is found then use the corresponding `user.remove_from_db()` function and return an empty JSON and 200.

Here are some tests that can be done to verify the implementation of POST, GET, PUT, DELETE.

```bash
> curl -X POST -H 'Content-Type: application/json' -d '{ "username": "admin", "password": "password123"}' http://localhost:5000/api/user
> curl http://localhost:5000/api/user/0
> curl -X PUT -H 'Content-Type: application/json' -d '{ "username": "admin", "password": "password12345"}' http://localhost:5000/api/user/0
> curl -X DELETE http://localhost:5000/api/user/0
```

#### Resources
- https://flask.palletsprojects.com/en/2.3.x/#api-reference
- https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/quickstart/
- https://github.com/bliutech/wikisafe/blob/main/server/app.py
---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by rebekah-wang**
## Summary

Closes #

### CODE REVIEW

**Review by bliutech — CHANGES_REQUESTED** [review]
@trishavreddy Would you mind running `black` to lint this code? That's currently why one of the GitHub Actions is failing. Inside your `server/` directory, make sure you have `black` installed with `pip install -r requirements.txt` and then run the following command.

```
python -m black *.py */*.py
```

This is mostly to make sure that all code is formatted properly. ✌️

**Comment by bliutech** [comment]
It also looks like you may be accidentally deleting some changes from the main branch. Could you run `git merge main` on your current branch locally. If you run into merge conflicts, let me know.

**Review by bliutech — CHANGES_REQUESTED** [review]
@trishavreddy Great work so far! I made a commit to this branch with some changes so I recommended pulling to take a look. These changes help set up some more boilerplate and fixed some problems with some of my recommended implementations being out of date with how the `Flask-SQLAlchemy` library current work. I added the implementations of `GET` and `POST` to provide some more guidance on how these sort of implementations should work but `PUT` and `DELETE` still need to be implemented. Make sure to check out #8 for more details on how to tackle this implementation. Reach out if you have any questions.

**Comment by bliutech** [comment]
Also, I recommend checking out how the Python `import` system [works](https://docs.python.org/3/reference/import.html). I am using some tricks such as dynamic imports to solve some problems such as circular dependencies with some parts of this application.

**Review by trishavreddy — APPROVED** [review]

**Review by ChL4859 — APPROVED** [review]

**Review by bliutech — CHANGES_REQUESTED** [review]
@trishavreddy I saw you merged another branch into this branch. Did you forget to add your own changes? Remember to do the following workflow on your branch.

```
git add -A
git commit -m "<your message"
git push
```

**Review by bliutech — APPROVED** [review]
Pushed minor adjustment to `delete` and adjusted to account for queries by `id` rather than `username`. Other than that, great job! Merging now. :D

**Pull request merged**
